version: 0.2

env:
  parameter-store:
    SONARQUBE_TOKEN: "SONARQUBE_ENDPOINT"
    SONARQUBE_ENDPOINT: "SONARQUBE_ENDPOINT"

phases:   
  install:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
      
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore MyWebApp.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build MyWebApp.csproj
      - sonar-scanner
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 --self-contained false MyWebApp.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: ./bin/Release/netcoreapp3.1/linux-x64/publish/
  discard-paths: no
