version: 0.2

env:
  variables:
    PROJECT: MyWebApp
    DOTNET_FRAMEWORK: 4.8
phases:
  build:
    commands:
      - msbuild $env:PROJECT.csproj /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:PackageAsSingleFile=false /p:OutDir=C:\codebuild\artifacts\ /t:Package
artifacts:
  files:
    - '**/*'
  base-directory: 'D:\Riyad\Job\DNExample\MyWebApp\${env:PROJECT}_Package\Archive\'
